version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    privileged: true
    depends_on:
      - app
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
  app:
    build: .
    image: quay.io/tasato/sample-nginx-nodejs
    init: true
    ports:
      - '3000:3000'
